In [1]:
list_1 = [1,2,3]

In [2]:
import numpy as np

In [4]:
arr = np.array(list_1)

In [5]:
arr

array([1, 2, 3])

In [6]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [7]:
arr = np.arange(25)

In [18]:
rarran = np.random.randint(0,100,25)

In [13]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [14]:
rarran

array([64,  8, 58, 66, 76, 14, 22, 60, 80, 95, 94, 48, 59, 78,  3, 80, 61,
        9, 53, 69, 16, 17, 75, 42,  0])

In [21]:
rarran

array([36, 93, 88, 65, 47, 39, 25, 91, 64, 17, 24, 52, 29, 90, 30,  0, 30,
       50, 87, 88,  5, 91, 20, 65, 17])

In [23]:
arr = np.arange(0,21)

In [24]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [26]:
arr[1:8]

array([1, 2, 3, 4, 5, 6, 7])

In [27]:
arr[-1:]

array([20])

In [28]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [29]:
arr[-7:]

array([14, 15, 16, 17, 18, 19, 20])

In [31]:
arr[0:10] = 1000

In [32]:
arr

array([1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000,   10,
         11,   12,   13,   14,   15,   16,   17,   18,   19,   20])

In [33]:
arr = np.arange(0,21)

In [34]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [35]:
arr_2d = np.array([[5,10,15],[15,20,25],[25,30,35]])

In [38]:
arr_2d[2][2]

35

In [39]:
arr_2d[2,2]

35

In [59]:
arr_2d

array([[ 5, 10, 15],
       [15, 20, 25],
       [25, 30, 35]])

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [60]:
arr[arr < 15]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [61]:
arr_2d = np.arange(50).reshape(5,10)

In [62]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [65]:
arr_2d[3:, 1:3]

array([[31, 32],
       [41, 42]])

In [69]:
arr_2d[2:4, 5:9]

array([[25, 26, 27, 28],
       [35, 36, 37, 38]])

In [70]:
arr_2d[1:4, 2:5]

array([[12, 13, 14],
       [22, 23, 24],
       [32, 33, 34]])

In [71]:
arr = np.arange(0,21)

In [73]:
arr + arr 

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40])

In [75]:
arr * (3+90-98)


array([   0,   -5,  -10,  -15,  -20,  -25,  -30,  -35,  -40,  -45,  -50,
        -55,  -60,  -65,  -70,  -75,  -80,  -85,  -90,  -95, -100])

In [76]:
arr/arr

/var/folders/mn/9qb2c4yj6438pm25byr3pbqm0000gq/T/ipykernel_69760/1862401812.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [77]:
arr ** arr

array([                   1,                    1,                    4,
                         27,                  256,                 3125,
                      46656,               823543,             16777216,
                  387420489,          10000000000,         285311670611,
              8916100448256,      302875106592253,    11112006825558016,
         437893890380859375,                    0, -2863221430593058543,
        -497033925936021504,  6353754964178307979, -2101438300051996672])

In [81]:
np.std(arr)

6.0553007081949835